export const selectors = {
	common: {
		heading: 'h1',
		lastPageButton: '.js-pagenav-last-button',
	},
	forum: {
		subForumLinks: '.forum-list-container .forum-item.sub a.forum-title',
		threadRow: '.topic-item.js-topic-item',
		threadTitle: '.topic-title.js-topic-title',
		threadAuthor: '.topic-info a[data-vbnamecard]',
		threadDate: '.topic-info .date',
		postsCount: '.posts-count',
		viewsCount: '.views-count',
		closedIcon: '.topic-closed-icon, .b-icon__locked, .b-icon__close',
	},
	thread: {
		post: '.b-post',
		person: '[itemtype="https://schema.org/Person"]',
		authorUrl: 'a[itemprop="url"]',
		memberLink: 'a[href*="/member/"]',
		timestampDate: '.b-post__timestamp .date',
		postcreatedDate: '.postcreated .date',
		time: 'time',
		postTitle: '.b-post__title',
		postTitleAlt: '.posttitle',
		postContent: '.js-post__content-text',
		postContentAlt: '.postcontent',
		attachments: '.js-post-attachments > ul > li > a',
		authorName: '[itemprop="name"]',
		editInfo: '.b-post__edit',
	},
	member: {
		aboutTab: 'a[data-url-path="about"]',
		aboutContainer: '#about-tab .js-profile-about-container > *',
		sidebarContent: '.widget-content.profile_sidebar_content > div',
		username: '.username',
		userTitle: '.usertitle',
		profileInfo: '.profile-info li, .profile-info div',
		totalPosts: '.about-stats-totalpost > div.section-content.table > div:nth-child(1) > div:nth-child(2)',
	},
} as const;
